plugins {
    id 'com.android.application'
}

android {
    namespace 'com.xfuture.budsloopback'
    compileSdk 35

    defaultConfig {
        applicationId 'com.xfuture.budsloopback'
        minSdk 23
        targetSdk 29
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
